### ISSUE TITLE
Initialization. Reward 4 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Storage-WRIO-App#2]
Please initialize app on OpsWorks AWS.
Storage is the app responsible for any kind of storing operations for AWS, Dropbox, etc.

**Comment by umairadeeb** [comment]
Configured against https://github.com/webRunes/Storage-WRIO-App/pull/4

**Comment by AlexeyAnshakov** [comment]
Please reconfig for s3 like it's done for 
>https://github.com/webRunes/Login-WRIO-App/edit/master/.travis.yml
